/*
 * This file was autogenerated by OSQP on Fri Jul 25 13:42:39 2025
 * 
 * This file contains a sample solver to run the embedded code.
 */

#include <stdio.h>
#include "osqp.h"
#include "workspace.h"
#include <time.h>

int main() {
  OSQPInt exitflag;

  printf( "Embedded test program for vector updates.\n");

  // 计算耗时
  clock_t start_time = clock();
  exitflag = osqp_solve( &solver );
  clock_t end_time = clock();
  double duration = (double)(end_time - start_time) / CLOCKS_PER_SEC;
  printf("  Solve time: %f seconds\n", duration);

  if( exitflag > 0 ) {
    printf( "  OSQP errored: %s\n", osqp_error_message(exitflag));
    return (int)exitflag;
  } else {
    printf( "  Solved workspace with no error.\n" );
  }
}
