/*
 * This file was autogenerated by OSQP on Fri Jul 25 13:42:39 2025
 * 
 * This file contains the configuration options needed by OSQP.
 */

#ifndef OSQP_CONFIGURE_H
#define OSQP_CONFIGURE_H

#define OSQP_ALGEBRA_BUILTIN
#define OSQP_EMBEDDED_MODE 1

#endif /* ifndef OSQP_CONFIGURE_H */
